### ISSUE TITLE
The interval has to be less than one day.

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-mobile#164]
Request: `https://sentry.io/api/0/organizations/sentry-sdks/sessions/?project=-1&interval=90d&statsPeriod=90d&field=sum%28session%29&groupBy=project`

`Org has no projects -> api error statusCode: 400 message: "{\"detail\":\"The interval has to be less than one day.\"}"`

https://sentry.io/organizations/sentry/issues/2269354795/?project=5645511&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3Ame_or_none

ref: https://github.com/getsentry/sentry/pull/24264

`interval=90d`
needs to be changed to `interval=1d`

**Comment by Swatinem** [comment]
This is actually a good example. Since we use numeric rounding based on unix timestamps for these, a 90d interval would do this:
```
const interval = 90 * 24 * 3600 * 1000;
new Date(Math.floor(Date.now() / interval)*interval).toISOString()
"2021-01-03T00:00:00.000Z"
new Date(Math.ceil(Date.now() / interval)*interval).toISOString()
"2021-04-03T00:00:00.000Z"
```
So the 90d interval would go from `2021-01-03` to `2021-04-03` for **every** day inside that period. So in early january, you would get basically only a weeks worth of sessions data, even though you *think* you get 90d.
