### ISSUE TITLE
Login Flow

### ISSUE THREAD

**Issue by denrase** [getsentry/sentry-mobile#5]
## I would propose the following flow for login:

- Initially, the application shows a login/signup screen. Some nice logo/designs and separate button fo sign-in and sign-up. When pressing those, the users are present a modal screen where with the respective website.
- We could only show the sign in button, if the intent is **not** to convert new users through the mobile app.
- After success-full login/register we present the tab bar layout with users stats and projects.

![Sentry Mobile - Login Flow](https://user-images.githubusercontent.com/3984453/97774928-4005df80-1b5c-11eb-951f-5716e45a90ca.png)

@HazAT @bruno-garcia What are your thoughts on this flow/approach?

## Considerations for iOS/Apple:

- Apple is requiring Sign-In with Apple if we have third-party systems for login in place. [Sign in with Apple](https://developer.apple.com/app-store/review/guidelines/#sign-in-with-apple)
- Those changes come into effect in 
- We have three options here:
  - 1.) Hope apple doesn't enforce the rule for a service like sentry mobile, as there seem to be some exceptions.
  - 2.) Add Apple as a third party option
  - 3.) Don't show the third party options

**Comment by HazAT** [comment]
I like the flow, it makes a lot of sense.
For now we can def. remove the sign-up button since this really should be a companion app to enrich your experience with Sentry, you don’t start with the app.

wrt Login with Apple; Let’s pray they understand we don’t need it here. 
Other we: 


![](https://i.kym-cdn.com/entries/icons/original/000/023/987/overcome.jpg)
